# Generated by Django 5.1.2 on 2024-11-14 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_customer_order_product_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
