# Generated by Django 5.1.5 on 2025-01-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
