# Generated by Django 5.1.5 on 2025-01-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
